name: Deploy to Cipres

on:
  push:
    branches: [prod]
  workflow_dispatch:

concurrency:
  group: "prod"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy to Cipres
        uses: appleboy/scp-action@v0.1.7
        with:
          host: cipres.cec.uchile.cl
          username: coheteriabeauchef
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "~/landing-page/"
          strip_components: 1
          rm: true

      - name: Fix permissions
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: cipres.cec.uchile.cl
          username: coheteriabeauchef
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: chmod -R go+rX ~/landing-page/
