name: Deploy to Cipres

on:
  push:
    branches: [prod]
  workflow_dispatch:

concurrency:
  group: "prod"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ASTRO_TELEMETRY_DISABLED: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm run build

      - name: Deploy to Cipres
        uses: appleboy/scp-action@v1
        with:
          host: cipres.cec.uchile.cl
          username: coheteriabeauchef
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "~/landing-page/"
          strip_components: 1
          rm: true

      - name: Fix permissions
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: cipres.cec.uchile.cl
          username: coheteriabeauchef
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: chmod -R go+rX ~/landing-page/
